### ISSUE TITLE
Path value should be saved as REG_EXPAND_SZ

### ISSUE THREAD

**Issue by PauloFrancaLacerda** [DGH2112/Path-Editor#1]
Hi.
I tried PathEditor for the first time yesterday, and noticed my batch files stopped working since then. Further investigations led to the cause: that tool recreated the "Path" value as a standard `REG_SZ` value. Thus, its values were not being expanded, obviously.

The solution is simple:
Just keep the `REG_EXPAND_SZ` type and Windows remains happy.  :D

P.S.
I haven't checked the source-code because I don't know "C". If it was coded in Delphi, I'd be able to fix it my myself.

**Comment by DGH2112** [comment]
That's a nice spot. I must admit that this happened on another machine and I couldn't work out why and strangely enough I've read the exact same thing somewhere in the last few days but I can't think where (probably Windows Internals or SysInternal).

I'll investigate tonight but might not get to fix it until tomorrow night.

The reason I wrote the project in C++ was to re-familiarize myself with it but I do prefer Delphi.

regards
Dave.

**Comment by DGH2112** [comment]
I’ve just done some research on the train on the way home and all I need to do is replace the TRegistry.WriteString() method with TRegistry.WriteExpandString().

This should be sorted tonight.

Regards
Dave

**Comment by DGH2112** [comment]
This has now been fixed in release 1.0c available from my web site as code and a binary or here in code.

regards
Dave.

**Comment by SirRufo** [comment]
FYI: The system default is
- for `HKLM\SYSTEM\CurrentControlSet\Control\SessionManager\Path` => `REG_EXPAND_SZ`
- for `HKCU\Environement\Path` => `REG_SZ`

I would suggest to not change the system defaults

**Comment by DGH2112** [comment]
Thanks for this. I'll tweak and updated tonight. BTW, where did you find this information?

regards
Dave.

**Comment by SirRufo** [comment]
I have had a look at the registry of an untouched windows installation (win8.1, win10).

The best option would be to just change the value and not the value kind, so we do not have to care for any future changes - but getting the valuekind is not implemented by embarcadero

See .Net [RegistryKey.GetValueKind( string )](https://msdn.microsoft.com/library/microsoft.win32.registrykey.getvaluekind(v=vs.110).aspx)

**Comment by DGH2112** [comment]
Its not possible to determine the existing kind for user paths if the profile doesn't existing in the first place which is the case on a new profile. I've check what happens if you use the built in tools and you are correct with your information.

regards
Dave.

**Comment by PauloFrancaLacerda** [comment]
The PATH usually contains %variables%, so it should always be expandable.

**Comment by DGH2112** [comment]
Paulo,
SirRudo is correct in that Window itself will only create a REG_SZ entry for a profile path.
Do you use variables in your profile path?

regards
Dave

**Comment by PauloFrancaLacerda** [comment]
Dave,
Since the installation of my Windows 7 x64, the PATH list begins with: `%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\system32\wbem;`
It was set like that by Windows itself, during installation.

The other entries (not shown above), were added by installers, and have no %variables% embedded.

**Comment by SirRufo** [comment]
Ok, now I have tested what windows (win8.1/win10) is doing with the path value/valuetype.

If the path contains a `%` then the value is stored as `REG_EXPAND_SZ` otherwise as `REG_SZ`.

That is an easy rule to implement :o)

**Comment by DGH2112** [comment]
I'll update and implement that rule as its easier than prompting for what type or typing to determine the existing type.

regards
Dave.

**Comment by DGH2112** [comment]
The code and binary has been updated to version 1.0d. It will create a REG_EXPAND_SZ strings IF the paths contains % character.

regards
Dave.
